### ISSUE TITLE
Suggestions for a Code of Conduct

### ISSUE THREAD

**Issue by mjbrender** [basho-labs/the-riak-community#48]
It's been brought to my attention we haven't formalized a code of conduct for our community. I'd love to do so and get feedback along the way.

**Comment by binarytemple** [comment]
[KDE code of conduct](https://www.kde.org/code-of-conduct/) is not bad, and it's CC.

**Comment by mjbrender** [comment]
I'd also recommend reference to anti-harassment policies: http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy

**Comment by danieldreier** [comment]
+1 to the geekfeminism policy examples.

**Comment by binarytemple** [comment]
"Booth staff (including volunteers) should not use sexualized clothing/uniforms/costumes, or otherwise create a sexualized [sic] environment."

Regardless of the underlying sociopolitical context, after decades of unshakable hindquarters upon chair placement this can only be a good thing for all concerned. Basho, keeping it classy ™.

**Comment by mjbrender** [comment]
FYI to @danieldreier & @binarytemple about the PR: #56

**Comment by mjbrender** [comment]
Now that @laurenrother has commented on #56, I feel good about moving it forward. Just an FYI to this thread.

**Comment by mjbrender** [comment]
It is done :+1:
