### ISSUE TITLE
Riak S2 Build process

### ISSUE THREAD

**Issue by mjbrender** [basho-labs/the-riak-community#69]
#Taishi member @sdebnath requested it. Shawn, could you elaborate here before you email on riak-users? We can build a document off of what's learned.

**Comment by sdebnath** [comment]
Sure. Working on getting CORS support in Riak CS/S2 (https://github.com/basho/riak_cs/issues/581). Since adding new features in riak cs usually involves multiple components, such as velvet, stanchion, and the riak_cs code itself, I was wondering if there was any documentation available for the build and test process to make lives easier for contributors to contribute high quality code. Also, guidance on what to do and what not to do would be much appreciated if available.

**Comment by mjbrender** [comment]
Hey @kuenishi, I'd love your feedback here or privately on our email if I need to do some documentation clean up before this could be consumed outside Basho. Thanks :smile:

**Comment by kuenishi** [comment]
Unfortunately we have few guidance other than in [README](https://github.com/basho/riak_cs#contributing-to-riak-cs) for contribution. Good news is during 2.1 development we included `velvet` into `riak_cs`, so we have only two specific code repository for S2 system.

**Comment by sdebnath** [comment]
Cool, been following that and realized velvet got incorporated into s2 repository. Will undo my changes from the separate velvet repo.
